version: "3.9"
services:
  # Main application service
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    volumes:
      - rag_storage:/app/storage/rag
      - app_logs:/app/logs
      - model_cache:/root/.cache/huggingface  # HuggingFace model cache
    networks:
      - multimodal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - multimodal_net
  #   restart: unless-stopped

  # Optional: Monitoring with basic metrics
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api
  #   networks:
  #     - multimodal_net
  #   restart: unless-stopped

volumes:
  rag_storage:
    driver: local
  app_logs:
    driver: local
  model_cache:
    driver: local
  # redis_data:
  #   driver: local

networks:
  multimodal_net:
    driver: bridge
